spring.application.name=Backend


## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb

#differ from db to another
#spring.datasource.username=
#spring.datasource.password=

# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=create-drop


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=roaa.m.elsayed@gmail.com
spring.mail.password=hlxe weat amqu iqas
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=665603013636-4q5rdlns1vsn254j42a2fqkg9p7nrc7p.apps.googleusercontent.com
