spring.application.name=Backend


## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/agarly
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#differ from db to another
spring.datasource.username=postgres
spring.datasource.password=roaa1222006

# create and drop table, good for testing, production set to none or comment it
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=create-drop

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=roaa.m.elsayed@gmail.com
spring.mail.password=exby gxpu szsw zfgs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=665603013636-4q5rdlns1vsn254j42a2fqkg9p7nrc7p.apps.googleusercontent.com
